# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ashley Peterson
title: .Net Developer
email: ashepterson177@gmail.com
website: www.ashpeterson.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username: https://github.com/ashpeterson
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: https://www.linkedin.com/in/ashp91
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ashley and I'm a .Net Developer. I specialize in software development, focusing on frameworks and integrations that meet customer needs.

  I am most skilled in: <mark>.Net</mark> and <mark>Problem Solving</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wexel Gaming
        link: wexelgaming.com
        sub_title: Software Developer
        caption: 2023 - Present
        quote: >
          Currently focused on back-end API development and front-end solutions.
        description: | # this will include new lines to allow paragraphs
          I am working on a back-end web API payments integration and front-end development using MVC and Vue.js, with PostgreSQL for data handling.

      - layout: left
        title: Self-Employed
        caption: 2020 - 2023
        sub_title: .Net Developer
        quote: >
          Developing software solutions tailored to various business needs.
        description: | # this will include new lines to allow paragraphs
          During my self-employment, I have worked on projects ranging from business ideas to side projects, including an integrated survey system and content management system. My expertise includes .Net Frameworks with C#, SQL, and Git for code management.

      - layout: left
        title: Select Legal Systems Ltd
        caption: 2019 - 2020
        sub_title: .Net Developer
        quote: >
          Implementing and improving software to meet customer demands.
        description: | # this will include new lines to allow paragraphs
          I was responsible for the implementation, maintenance, and improvement of software solutions. My main project was developing a document search engine and a voice-dictation service. Technologies used include .Net Frameworks, C#, VB.Net, SQL, and Microsoft DevOps.

      - layout: left
        title: Cranswick PLC
        caption: 2018 - 2019
        sub_title: IT Analyst Intern
        quote: >
          Forming solutions for critical business problems.
        description: | # this will include new lines to allow paragraphs
          My roles included investigating business problems and developing solutions through technical implementations, using Microsoft NAV and C/AL, Power BI for data analytics, and .Net Frameworks with C# and SQL.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Open University
        caption: 2021 - Present
        sub_title: MSc Systems Thinking

      - layout: left
        title: Hull University
        caption: 2016 - 2020
        sub_title: BSc Computer Science with Information Systems

  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Expertise
        description: | # this will include new lines to allow paragraphs
          - C#
          - .Net Frameworks
          - SQL
          - Git & DevOps
          - Scrum

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering, some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
